ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - init: ./bin/setup.sh
    command: yarn dev

vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - matklad.rust-analyzer
    - donjayamanne.git-extension-pack